sudo: required

language: bash

services:
  - docker

before_install:
  - docker build -t test-service .
  - docker run -d --name test-service test-service
  - pip install requests

script:
  - docker ps | grep -q test-service
