sudo: required

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull madnight/alpine-wkhtmltopdf-builder:0.12.5-alpine3.10 || true
  - docker build
    --cache-from madnight/alpine-wkhtmltopdf-builder:0.12.5-alpine3.10
    -f src/Dockerfile .
    -t madnight/alpine-wkhtmltopdf-builder:0.12.5-alpine3.10
    -t madnight/alpine-wkhtmltopdf-builder:0.12.5-alpine3.10-"$TRAVIS_JOB_ID"
  - docker push madnight/alpine-wkhtmltopdf-builder:0.12.5-alpine3.10
  - docker push madnight/alpine-wkhtmltopdf-builder:0.12.5-alpine3.10-"$TRAVIS_JOB_ID"
  - docker build -t madnight/alpine-wkhtmltopdf .
  - sudo apt-get -qq update
  - sudo apt-get install -y poppler-utils

script:
  - docker run -P madnight/alpine-wkhtmltopdf -q google.com - - > test.pdf
  - pdftotext -layout test.pdf - | grep -q Google
